### ISSUE TITLE
Create map to plot locations

### ISSUE THREAD

**Issue by kngurley25** [hkapk/trippin-worldwide#17]

**Comment by kngurley25** [comment]
https://www.npmjs.com/package/@newamerica/maps

**Comment by kngurley25** [comment]
https://www.npmjs.com/package/chartjs-chart-geo

**Comment by christinedbaxter** [comment]
Used Google Maps API:
- [Geocoding API](https://developers.google.com/maps/documentation/geocoding/overview?hl=en_US) (for getting latitude and longitude using city name)
- [Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/overview?hl=en_US) (for customizing maps with your own content and imagery for display on web pages and mobile devices)
